### ISSUE TITLE
Need support for latest Node (0.12.x) and iojs (3.x.x)

### ISSUE THREAD

**Issue by micky2be** [Wizcorp/Jeff#10]
As far as I know support for iojs might be difficult or takes time due to some (sub)dependencies that need to use and update the codebase for nan 2.x.x

Support for node 0.12.x should be a must have in my opinion.

**Comment by bchevalier** [comment]
It depends on whether more that one project uses Jeff.

**Comment by micky2be** [comment]
Well, I use Jeff on my project and use iojs 3 on it. Can make the effort for node 0.12.x though.

**Comment by bchevalier** [comment]
The chances for these supports to happen are higher if someone contributed.

**Comment by ronkorving** [comment]
This should no longer be relevant.
