### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by ronkorving** [Wizcorp/Jeff#27]
The readme refers to http://www.jeff.github.io/ for "all options", but that URL does not exist.

**Comment by bchevalier** [comment]
Actually it could have been removed in your [PR](https://github.com/Wizcorp/Jeff/pull/26).
I forgot how that link was supposed to work or if it ever worked.

**Comment by ronkorving** [comment]
Yeah, I can't find any place where this documentation would exist. So unfortunately for now, I will remove the link.
